<a href="https://colab.research.google.com/github/anshatwork-007/Data-Normalization/blob/main/Experiment_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: Ansh Yadav
# Branch: ENTC A1
# Batch: 2025-29
# Experiment 14

## Title: Data Normalization

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Product": ['laptop', 'mobile', 'tablet', 'headphone', 'smartwatch', 'camera'],
    'Price': [55000,20000,30000,2000,8000,45000],
    'Units_Sold': [25,60,35,80,50,15],
    'Discount': [10,15,12,20,18,8]
}

df = pd.DataFrame(data)

print("Original Dataset")
print(df)

Original Dataset
      Product  Price  Units_Sold  Discount
0      laptop  55000          25        10
1      mobile  20000          60        15
2      tablet  30000          35        12
3   headphone   2000          80        20
4  smartwatch   8000          50        18
5      camera  45000          15         8

In [ ]:
# 1 Min-Max Normalization

df['Price_Min-Max'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price")
print(df[['Product','Price','Price_Min-Max']])

Min-Max Normalized Price
      Product  Price  Price_Min-Max
0      laptop  55000       1.000000
1      mobile  20000       0.339623
2      tablet  30000       0.528302
3   headphone   2000       0.000000
4  smartwatch   8000       0.113208
5      camera  45000       0.811321

In [ ]:
# Normalize multiple columns
cols = ['Price', 'Units_Sold', 'Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
# Z-score Normalization

df['Units_Z-score'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print("\nZ-score Normalized Units_Sold")
print(df[['Product','Units_Sold','Units_Z-score']])

Z-score Normalized Units_Sold
      Product  Units_Sold  Units_Z-score
0      laptop          25      -0.799885
1      mobile          60       0.660775
2      tablet          35      -0.382554
3   headphone          80       1.495437
4  smartwatch          50       0.243443
5      camera          15      -1.217216

In [ ]:
# Decimal Scaling

df['Price_Decimals'] = df['Price']/100000
print("\nDecimal Scaled Price")
print(df[['Product','Price','Price_Decimals']])

Decimal Scaled Price
      Product  Price  Price_Decimals
0      laptop  55000            0.55
1      mobile  20000            0.20
2      tablet  30000            0.30
3   headphone   2000            0.02
4  smartwatch   8000            0.08
5      camera  45000            0.45

In [ ]:
# Data set
df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# MinMax Normalization
# Normalize all columns
df['Price_Min-Max'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
df['Rating_Min-Max'] = (df['Rating'] - df['Rating'].min()) / (df['Rating'].max() - df['Rating'].min())
df['Reviews_Min-Max'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max() - df['Reviews'].min())
df['Units_Sold_Min-Max'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())

print(df[['Product_Name','Price','Price_Min-Max','Rating','Rating_Min-Max','Reviews','Reviews_Min-Max','Units_Sold','Units_Sold_Min-Max']])

                   Product_Name  Price  Price_Min-Max  Rating  Rating_Min-Max  \
0                Wireless Mouse    799       0.020243     4.3        0.428571
1             Bluetooth Speaker   1499       0.048583     4.5        0.714286
2                  USB Keyboard    699       0.016194     4.1        0.142857
3                Gaming Headset   2499       0.089069     4.6        0.857143
4                    Smartwatch   3999       0.149798     4.4        0.571429
5                    Power Bank   1199       0.036437     4.2        0.285714
6                  Laptop Stand    899       0.024291     4.0        0.000000
7                        Webcam   1899       0.064777     4.3        0.428571
8                  Portable SSD   5499       0.210526     4.7        1.000000
9              Wireless Charger    999       0.028340     4.2        0.285714
10  Noise Cancelling Headphones   7999       0.311741     4.6        0.857143
11          Mechanical Keyboard   4599       0.174089     4.5        0.714286
12                 Gaming Mouse   1599       0.052632     4.4        0.571429
13                 Tablet Stand    699       0.016194     4.1        0.142857
14                      USB Hub    899       0.024291     4.2        0.285714
15          External Hard Drive   6499       0.251012     4.6        0.857143
16            Smartphone Tripod   1199       0.036437     4.3        0.428571
17              Laptop Backpack   1999       0.068826     4.4        0.571429
18            Bluetooth Earbuds   2999       0.109312     4.5        0.714286
19                LED Desk Lamp   1299       0.040486     4.3        0.428571
20                 Phone Holder    499       0.008097     4.0        0.000000
21            Wireless Keyboard   2499       0.089069     4.4        0.571429
22             Portable Monitor   8999       0.352227     4.6        0.857143
23                   Smart Plug    799       0.020243     4.2        0.285714
24                  WiFi Router   3499       0.129555     4.5        0.714286
25              Graphics Tablet   4599       0.174089     4.4        0.571429
26                   VR Headset  12999       0.514170     4.7        1.000000
27                   Microphone   2199       0.076923     4.3        0.428571
28             Smart Light Bulb    699       0.016194     4.2        0.285714
29           Laptop Cooling Pad   1499       0.048583     4.3        0.428571
30                Action Camera   9999       0.392713     4.6        0.857143
31               Smart Doorbell   5999       0.230769     4.5        0.714286
32              Streaming Stick   3499       0.129555     4.4        0.571429
33           Portable Projector  11999       0.473684     4.6        0.857143
34                 Gaming Chair  15999       0.635628     4.7        1.000000
35               Desk Organizer    599       0.012146     4.1        0.142857
36              USB Flash Drive    799       0.020243     4.2        0.285714
37       Phone Screen Protector    299       0.000000     4.0        0.000000
38                Laptop Sleeve    999       0.028340     4.3        0.428571
39           Wireless Presenter   1499       0.048583     4.4        0.571429
40         Tablet Keyboard Case   2999       0.109312     4.5        0.714286
41             Smart Thermostat  10999       0.433198     4.6        0.857143
42              Security Camera   4999       0.190283     4.4        0.571429
43                 Drone Camera  24999       1.000000     4.7        1.000000
44              Electric Kettle   1999       0.068826     4.3        0.428571
45                    Air Fryer   7999       0.311741     4.6        0.857143
46                 Robot Vacuum  18999       0.757085     4.5        0.714286
47                  Smart Scale   2499       0.089069     4.4        0.571429
48          Digital Photo Frame   3499       0.129555     4.3        0.428571
49                 Portable Fan    999       0.028340     4.2        0.285714

    Reviews  Reviews_Min-Max  Units_Sold  Units_Sold_Min-Max
0      1520         0.291005         350            0.518519
1       980         0.148148         220            0.277778
2       870         0.119048         180            0.203704
3      2100         0.444444         410            0.629630
4      3050         0.695767         520            0.833333
5      1750         0.351852         390            0.592593
6       620         0.052910         140            0.129630
7      1120         0.185185         260            0.351852
8      1850         0.378307         330            0.481481
9       760         0.089947         190            0.222222
10     4200         1.000000         610            1.000000
11     2100         0.444444         290            0.407407
12     1300         0.232804         340            0.500000
13      540         0.031746         120            0.092593
14      870         0.119048         200            0.240741
15     2300         0.497354         310            0.444444
16      760         0.089947         210            0.259259
17     1600         0.312169         420            0.648148
18     3500         0.814815         530            0.851852
19      980         0.148148         260            0.351852
20      420         0.000000         150            0.148148
21     1450         0.272487         310            0.444444
22     1250         0.219577         170            0.185185
23      720         0.079365         210            0.259259
24     2100         0.444444         390            0.592593
25      980         0.148148         160            0.166667
26     3100         0.708995         140            0.129630
27     1300         0.232804         270            0.370370
28      880         0.121693         240            0.314815
29      990         0.150794         260            0.351852
30     2100         0.444444         200            0.240741
31     1750         0.351852         180            0.203704
32     2500         0.550265         430            0.666667
33     1450         0.272487         120            0.092593
34     2100         0.444444          90            0.037037
35      450         0.007937         160            0.166667
36      900         0.126984         320            0.462963
37      600         0.047619         380            0.574074
38      720         0.079365         210            0.259259
39      520         0.026455         130            0.111111
40      850         0.113757         150            0.148148
41     1200         0.206349         110            0.074074
42     2100         0.444444         260            0.351852
43     1800         0.365079          70            0.000000
44     1400         0.259259         310            0.444444
45     2200         0.470899         200            0.240741
46     1650         0.325397         120            0.092593
47      980         0.148148         170            0.185185
48      870         0.119048         150            0.148148
49      760         0.089947         240            0.314815

In [ ]:
cols = ['Price', 'Rating', 'Reviews','Units_Sold']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalized Data:")
print(df_norm)

Normalized Data:
       Price    Rating   Reviews  Units_Sold
0   0.020243  0.428571  0.291005    0.518519
1   0.048583  0.714286  0.148148    0.277778
2   0.016194  0.142857  0.119048    0.203704
3   0.089069  0.857143  0.444444    0.629630
4   0.149798  0.571429  0.695767    0.833333
5   0.036437  0.285714  0.351852    0.592593
6   0.024291  0.000000  0.052910    0.129630
7   0.064777  0.428571  0.185185    0.351852
8   0.210526  1.000000  0.378307    0.481481
9   0.028340  0.285714  0.089947    0.222222
10  0.311741  0.857143  1.000000    1.000000
11  0.174089  0.714286  0.444444    0.407407
12  0.052632  0.571429  0.232804    0.500000
13  0.016194  0.142857  0.031746    0.092593
14  0.024291  0.285714  0.119048    0.240741
15  0.251012  0.857143  0.497354    0.444444
16  0.036437  0.428571  0.089947    0.259259
17  0.068826  0.571429  0.312169    0.648148
18  0.109312  0.714286  0.814815    0.851852
19  0.040486  0.428571  0.148148    0.351852
20  0.008097  0.000000  0.000000    0.148148
21  0.089069  0.571429  0.272487    0.444444
22  0.352227  0.857143  0.219577    0.185185
23  0.020243  0.285714  0.079365    0.259259
24  0.129555  0.714286  0.444444    0.592593
25  0.174089  0.571429  0.148148    0.166667
26  0.514170  1.000000  0.708995    0.129630
27  0.076923  0.428571  0.232804    0.370370
28  0.016194  0.285714  0.121693    0.314815
29  0.048583  0.428571  0.150794    0.351852
30  0.392713  0.857143  0.444444    0.240741
31  0.230769  0.714286  0.351852    0.203704
32  0.129555  0.571429  0.550265    0.666667
33  0.473684  0.857143  0.272487    0.092593
34  0.635628  1.000000  0.444444    0.037037
35  0.012146  0.142857  0.007937    0.166667
36  0.020243  0.285714  0.126984    0.462963
37  0.000000  0.000000  0.047619    0.574074
38  0.028340  0.428571  0.079365    0.259259
39  0.048583  0.571429  0.026455    0.111111
40  0.109312  0.714286  0.113757    0.148148
41  0.433198  0.857143  0.206349    0.074074
42  0.190283  0.571429  0.444444    0.351852
43  1.000000  1.000000  0.365079    0.000000
44  0.068826  0.428571  0.259259    0.444444
45  0.311741  0.857143  0.470899    0.240741
46  0.757085  0.714286  0.325397    0.092593
47  0.089069  0.571429  0.148148    0.185185
48  0.129555  0.428571  0.119048    0.148148
49  0.028340  0.285714  0.089947    0.314815

In [ ]:
# Z-Score Normalization
df['Rating_zscore'] = (df['Rating'] - df['Rating'].mean()) / df['Rating'].std()
print("\nZ-Score Normalized Rating:")
print(df[['Product_Name','Rating','Rating_zscore']])

Z-Score Normalized Rating:
                   Product_Name  Rating  Rating_zscore
0                Wireless Mouse     4.3      -0.421580
1             Bluetooth Speaker     4.5       0.606665
2                  USB Keyboard     4.1      -1.449825
3                Gaming Headset     4.6       1.120787
4                    Smartwatch     4.4       0.092542
5                    Power Bank     4.2      -0.935703
6                  Laptop Stand     4.0      -1.963948
7                        Webcam     4.3      -0.421580
8                  Portable SSD     4.7       1.634910
9              Wireless Charger     4.2      -0.935703
10  Noise Cancelling Headphones     4.6       1.120787
11          Mechanical Keyboard     4.5       0.606665
12                 Gaming Mouse     4.4       0.092542
13                 Tablet Stand     4.1      -1.449825
14                      USB Hub     4.2      -0.935703
15          External Hard Drive     4.6       1.120787
16            Smartphone Tripod     4.3      -0.421580
17              Laptop Backpack     4.4       0.092542
18            Bluetooth Earbuds     4.5       0.606665
19                LED Desk Lamp     4.3      -0.421580
20                 Phone Holder     4.0      -1.963948
21            Wireless Keyboard     4.4       0.092542
22             Portable Monitor     4.6       1.120787
23                   Smart Plug     4.2      -0.935703
24                  WiFi Router     4.5       0.606665
25              Graphics Tablet     4.4       0.092542
26                   VR Headset     4.7       1.634910
27                   Microphone     4.3      -0.421580
28             Smart Light Bulb     4.2      -0.935703
29           Laptop Cooling Pad     4.3      -0.421580
30                Action Camera     4.6       1.120787
31               Smart Doorbell     4.5       0.606665
32              Streaming Stick     4.4       0.092542
33           Portable Projector     4.6       1.120787
34                 Gaming Chair     4.7       1.634910
35               Desk Organizer     4.1      -1.449825
36              USB Flash Drive     4.2      -0.935703
37       Phone Screen Protector     4.0      -1.963948
38                Laptop Sleeve     4.3      -0.421580
39           Wireless Presenter     4.4       0.092542
40         Tablet Keyboard Case     4.5       0.606665
41             Smart Thermostat     4.6       1.120787
42              Security Camera     4.4       0.092542
43                 Drone Camera     4.7       1.634910
44              Electric Kettle     4.3      -0.421580
45                    Air Fryer     4.6       1.120787
46                 Robot Vacuum     4.5       0.606665
47                  Smart Scale     4.4       0.092542
48          Digital Photo Frame     4.3      -0.421580
49                 Portable Fan     4.2      -0.935703

In [ ]:
# Decimal scaling
df['Price_decimal'] = df['Price']/ 100000
print('\ndecimal scaling')
print(df)

decimal scaling
   Product_ID                 Product_Name  Price  Rating  Reviews  \
0        P101               Wireless Mouse    799     4.3     1520
1        P102            Bluetooth Speaker   1499     4.5      980
2        P103                 USB Keyboard    699     4.1      870
3        P104               Gaming Headset   2499     4.6     2100
4        P105                   Smartwatch   3999     4.4     3050
5        P106                   Power Bank   1199     4.2     1750
6        P107                 Laptop Stand    899     4.0      620
7        P108                       Webcam   1899     4.3     1120
8        P109                 Portable SSD   5499     4.7     1850
9        P110             Wireless Charger    999     4.2      760
10       P111  Noise Cancelling Headphones   7999     4.6     4200
11       P112          Mechanical Keyboard   4599     4.5     2100
12       P113                 Gaming Mouse   1599     4.4     1300
13       P114                 Tablet Stand    699     4.1      540
14       P115                      USB Hub    899     4.2      870
15       P116          External Hard Drive   6499     4.6     2300
16       P117            Smartphone Tripod   1199     4.3      760
17       P118              Laptop Backpack   1999     4.4     1600
18       P119            Bluetooth Earbuds   2999     4.5     3500
19       P120                LED Desk Lamp   1299     4.3      980
20       P121                 Phone Holder    499     4.0      420
21       P122            Wireless Keyboard   2499     4.4     1450
22       P123             Portable Monitor   8999     4.6     1250
23       P124                   Smart Plug    799     4.2      720
24       P125                  WiFi Router   3499     4.5     2100
25       P126              Graphics Tablet   4599     4.4      980
26       P127                   VR Headset  12999     4.7     3100
27       P128                   Microphone   2199     4.3     1300
28       P129             Smart Light Bulb    699     4.2      880
29       P130           Laptop Cooling Pad   1499     4.3      990
30       P131                Action Camera   9999     4.6     2100
31       P132               Smart Doorbell   5999     4.5     1750
32       P133              Streaming Stick   3499     4.4     2500
33       P134           Portable Projector  11999     4.6     1450
34       P135                 Gaming Chair  15999     4.7     2100
35       P136               Desk Organizer    599     4.1      450
36       P137              USB Flash Drive    799     4.2      900
37       P138       Phone Screen Protector    299     4.0      600
38       P139                Laptop Sleeve    999     4.3      720
39       P140           Wireless Presenter   1499     4.4      520
40       P141         Tablet Keyboard Case   2999     4.5      850
41       P142             Smart Thermostat  10999     4.6     1200
42       P143              Security Camera   4999     4.4     2100
43       P144                 Drone Camera  24999     4.7     1800
44       P145              Electric Kettle   1999     4.3     1400
45       P146                    Air Fryer   7999     4.6     2200
46       P147                 Robot Vacuum  18999     4.5     1650
47       P148                  Smart Scale   2499     4.4      980
48       P149          Digital Photo Frame   3499     4.3      870
49       P150                 Portable Fan    999     4.2      760

    Units_Sold  Price_Min-Max  Rating_Min-Max  Reviews_Min-Max  \
0          350       0.020243        0.428571         0.291005
1          220       0.048583        0.714286         0.148148
2          180       0.016194        0.142857         0.119048
3          410       0.089069        0.857143         0.444444
4          520       0.149798        0.571429         0.695767
5          390       0.036437        0.285714         0.351852
6          140       0.024291        0.000000         0.052910
7          260       0.064777        0.428571         0.185185
8          330       0.210526        1.000000         0.378307
9          190       0.028340        0.285714         0.089947
10         610       0.311741        0.857143         1.000000
11         290       0.174089        0.714286         0.444444
12         340       0.052632        0.571429         0.232804
13         120       0.016194        0.142857         0.031746
14         200       0.024291        0.285714         0.119048
15         310       0.251012        0.857143         0.497354
16         210       0.036437        0.428571         0.089947
17         420       0.068826        0.571429         0.312169
18         530       0.109312        0.714286         0.814815
19         260       0.040486        0.428571         0.148148
20         150       0.008097        0.000000         0.000000
21         310       0.089069        0.571429         0.272487
22         170       0.352227        0.857143         0.219577
23         210       0.020243        0.285714         0.079365
24         390       0.129555        0.714286         0.444444
25         160       0.174089        0.571429         0.148148
26         140       0.514170        1.000000         0.708995
27         270       0.076923        0.428571         0.232804
28         240       0.016194        0.285714         0.121693
29         260       0.048583        0.428571         0.150794
30         200       0.392713        0.857143         0.444444
31         180       0.230769        0.714286         0.351852
32         430       0.129555        0.571429         0.550265
33         120       0.473684        0.857143         0.272487
34          90       0.635628        1.000000         0.444444
35         160       0.012146        0.142857         0.007937
36         320       0.020243        0.285714         0.126984
37         380       0.000000        0.000000         0.047619
38         210       0.028340        0.428571         0.079365
39         130       0.048583        0.571429         0.026455
40         150       0.109312        0.714286         0.113757
41         110       0.433198        0.857143         0.206349
42         260       0.190283        0.571429         0.444444
43          70       1.000000        1.000000         0.365079
44         310       0.068826        0.428571         0.259259
45         200       0.311741        0.857143         0.470899
46         120       0.757085        0.714286         0.325397
47         170       0.089069        0.571429         0.148148
48         150       0.129555        0.428571         0.119048
49         240       0.028340        0.285714         0.089947

    Units_Sold_Min-Max  Rating_zscore  Price_decimal
0             0.518519      -0.421580        0.00799
1             0.277778       0.606665        0.01499
2             0.203704      -1.449825        0.00699
3             0.629630       1.120787        0.02499
4             0.833333       0.092542        0.03999
5             0.592593      -0.935703        0.01199
6             0.129630      -1.963948        0.00899
7             0.351852      -0.421580        0.01899
8             0.481481       1.634910        0.05499
9             0.222222      -0.935703        0.00999
10            1.000000       1.120787        0.07999
11            0.407407       0.606665        0.04599
12            0.500000       0.092542        0.01599
13            0.092593      -1.449825        0.00699
14            0.240741      -0.935703        0.00899
15            0.444444       1.120787        0.06499
16            0.259259      -0.421580        0.01199
17            0.648148       0.092542        0.01999
18            0.851852       0.606665        0.02999
19            0.351852      -0.421580        0.01299
20            0.148148      -1.963948        0.00499
21            0.444444       0.092542        0.02499
22            0.185185       1.120787        0.08999
23            0.259259      -0.935703        0.00799
24            0.592593       0.606665        0.03499
25            0.166667       0.092542        0.04599
26            0.129630       1.634910        0.12999
27            0.370370      -0.421580        0.02199
28            0.314815      -0.935703        0.00699
29            0.351852      -0.421580        0.01499
30            0.240741       1.120787        0.09999
31            0.203704       0.606665        0.05999
32            0.666667       0.092542        0.03499
33            0.092593       1.120787        0.11999
34            0.037037       1.634910        0.15999
35            0.166667      -1.449825        0.00599
36            0.462963      -0.935703        0.00799
37            0.574074      -1.963948        0.00299
38            0.259259      -0.421580        0.00999
39            0.111111       0.092542        0.01499
40            0.148148       0.606665        0.02999
41            0.074074       1.120787        0.10999
42            0.351852       0.092542        0.04999
43            0.000000       1.634910        0.24999
44            0.444444      -0.421580        0.01999
45            0.240741       1.120787        0.07999
46            0.092593       0.606665        0.18999
47            0.185185       0.092542        0.02499
48            0.148148      -0.421580        0.03499
49            0.314815      -0.935703        0.00999

In [ ]:
# Turning Categorical Variables into quantitative variables
import pandas as pd

data = {
    'Order_ID': [101, 102, 103, 104, 105, 106],
    'Customer_Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'Payment_Method': ['UPI', 'Credit Card', 'Debit Card', 'COD', 'UPI', 'Debit Card'],
    'Product_Category': ['Electronics', 'Clothing', 'Home', 'Electronics', 'Beauty', 'Electronics'],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Hyderabad'],
    'Order_Value': [4500, 2300, 3200, 5200, 1800, 4100]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the output
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
# Method 1:Label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value  Gender_Label
0         4500             1
1         2300             0
2         3200             0
3         5200             1
4         1800             0
5         4100             1

In [ ]:
# Method 2 Gate dummies
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])

print(df_encoded)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105          Female           Beauty       Pune         1800
5       106            Male      Electronics  Hyderabad         4100

   Gender_Label  Payment_Method_COD  Payment_Method_Credit Card  \
0             1               False                       False
1             0               False                        True
2             0               False                       False
3             1                True                       False
4             0               False                       False
5             1               False                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [ ]:
# Encoding Multiple columns

df_multi = pd.get_dummies(df, columns=['Product_Category','City'])

print(df_multi)

   Order_ID Customer_Gender Payment_Method  Order_Value  Gender_Label  \
0       101            Male            UPI         4500             1
1       102          Female    Credit Card         2300             0
2       103          Female     Debit Card         3200             0
3       104            Male            COD         5200             1
4       105          Female            UPI         1800             0
5       106            Male     Debit Card         4100             1

   Product_Category_Beauty  Product_Category_Clothing  \
0                    False                      False
1                    False                       True
2                    False                      False
3                    False                      False
4                     True                      False
5                    False                      False

   Product_Category_Electronics  Product_Category_Home  City_Bangalore  \
0                          True                  False           False
1                         False                  False           False
2                         False                   True           False
3                          True                  False            True
4                         False                  False           False
5                          True                  False           False

   City_Delhi  City_Hyderabad  City_Mumbai  City_Pune
0       False           False        False       True
1       False           False         True      False
2        True           False        False      False
3       False           False        False      False
4       False           False        False       True
5       False            True        False      False

In [ ]:
# Method 3: Dummy encoding( Drop First)

df_dummy = pd.get_dummies(df, columns=['Product_Category'], drop_first=True)

print(df_dummy)

   Order_ID Customer_Gender Payment_Method       City  Order_Value  \
0       101            Male            UPI       Pune         4500
1       102          Female    Credit Card     Mumbai         2300
2       103          Female     Debit Card      Delhi         3200
3       104            Male            COD  Bangalore         5200
4       105          Female            UPI       Pune         1800
5       106            Male     Debit Card  Hyderabad         4100

   Gender_Label  Product_Category_Clothing  Product_Category_Electronics  \
0             1                      False                          True
1             0                       True                         False
2             0                      False                         False
3             1                      False                          True
4             0                      False                         False
5             1                      False                          True

   Product_Category_Home
0                  False
1                  False
2                   True
3                  False
4                  False
5                  False

In [ ]:
# Data set 2
df = pd.read_csv("/content/Student-Dataset.csv")
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# Medtuod 1
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Gender'])

print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Gender_Label
0                     92           Placed  450000             0
1                     85       Not Placed       0             1
2                     96           Placed  550000             0
3                     78       Not Placed       0             1
4                     88           Placed  480000             0
5                     72       Not Placed       0             1
6                     91           Placed  500000             0
7                     80       Not Placed       0             1
8                     84           Placed  420000             0
9                     76       Not Placed       0             1

In [ ]:
# Method 2
df_multi = pd.get_dummies(df, columns=['Department','Placement_Status'])

print(df_multi)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  Salary  \
0      101  Female   8.2                   0                     92  450000
1      102    Male   7.5                   1                     85       0
2      103  Female   9.1                   0                     96  550000
3      104    Male   6.8                   2                     78       0
4      105  Female   8.7                   0                     88  480000
5      106    Male   7.2                   3                     72       0
6      107  Female   8.9                   0                     91  500000
7      108    Male   6.5                   1                     80       0
8      109  Female   7.8                   0                     84  420000
9      110    Male   7.0                   2                     76       0

   Department_Civil  Department_Computer  Department_ENTC  Department_IT  \
0             False                 True            False          False
1             False                False            False           True
2             False                False             True          False
3             False                False            False          False
4             False                 True            False          False
5              True                False            False          False
6             False                False            False           True
7             False                 True            False          False
8             False                False             True          False
9             False                False            False          False

   Department_Mechanical  Placement_Status_Not Placed  Placement_Status_Placed
0                  False                        False                     True
1                  False                         True                    False
2                  False                        False                     True
3                   True                         True                    False
4                  False                        False                     True
5                  False                         True                    False
6                  False                        False                     True
7                  False                         True                    False
8                  False                        False                     True
9                   True                         True                    False

In [ ]:
# Method 3
import pandas as pd

df = pd.read_csv("/content/Student-Dataset.csv")
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

df_dummy

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,False,False,False,True